### ISSUE TITLE
Getting an error () if I get spaces or an id

### ISSUE THREAD

**Issue by rays** [alvariumhex/confluence-rs#2]
```let confluence = atlas_confluence::Session::new(
        "foo@bar.com".to_owned(),
        "abc123".to_owned(),
        "https://ffoo.atlassian.net/wiki/rest/api/".to_owned(),
    );
    let result = confluence.get_spaces().await;
    if let Err(e) = result {
        println!("Error: {:#?}", e);
    }
```
returns `Error: ()` I am not sure what I might be doing wrong.

**Comment by xunafay** [comment]
Hey, this library was quickly written to support a PoC on an internal tool.
you're issue is likely to exist at [this line](https://github.com/alvariumhex/confluence-rs/blob/95b5012660167db457112c944be863a333c68fbb/src/lib.rs#L65C16-L65C16)
I will update the code to return the error properly. But you can for now use a logger library to see what the error is

If I may wager a guess it's because my code assumes no slashes at the end of the base url

**Comment by rays** [comment]
```[2023-09-28T20:26:29Z ERROR atlas_confluence] Error getting page: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>404</status-code><message>null for uri: https://foo.atlassian.net/wiki/rest/api/rest/api/content/12345?expand=body.view%2Cspace%2Cchildren.page</message></status>```

I tried with and without the trailing slash in my url and get the same 404 error

**Comment by rays** [comment]
figured it out, url needs to be `https://foo.atlassian.net/wiki`

**Comment by xunafay** [comment]
Ah I missed that too, I'll add some example documentation
